#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2022 Marc Khouzam  <marc.khouzam@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This script provides shell completion for the kubectl pluugin-completion plugin

if [ $# -eq 1 ]; then
    if [[ "$1" == "-"* ]]; then
		echo "-h"
		echo "--help"
    elif [[ "$1" == "--"* ]]; then
		echo "--help"
	else
		tab=$(printf '\t')
		echo "setup${tab}Setup all possible plugin shell completions"
		echo "list${tab}List the plugins for which shell completion was setup by this plugin"
		echo "clean${tab}Remove all shell completions that were setup by this plugin"
		echo "supported${tab}List the plugins for which shell completion can be setup"
	fi
fi

echo ":4" # No file completion	
