apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: plugin-completion
spec:
  homepage: https://github.com/marckhouzam/kubectl-plugin_completion
  shortDescription: Generate shell completion scripts for different kubectl plugins
  version: v0.1.0
  description: |
    Enable shell completion for some installed plugins (supports over 50% of krew plugins).
  caveats: |
    kubectl v1.24 is required for shell completion to work for plugins.

    This plugin will only activate shell completion for plugins that use the
    popular Cobra Go library (https://github.com/spf13/cobra).

    Although just as effective, this plugin is a temporary solution until your
    favorite plugins provide shell completion themselves.
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    uri: https://github.com/marckhouzam/kubectl-plugin_completion/releases/download/v0.1.0/plugin-completion.tar.gz
    sha256: 379fc96afb66f79227bac5464924dd1a553b19fd0dfa47cce8ba0c96c3cfe46c
    bin: kubectl-plugin_completion
    files:
    - from: kubectl-plugin_completion
      to: .
    - from: LICENSE
      to: .
